### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by benl95** [theonejonahgold/functional-programming#1]
Deze datasets zouden handig kunnen zijn m.b.t. je onderzoek:

[Actuele beschikbaarheid Parkeergarages](https://data.amsterdam.nl/datasets/9ORkef6T-aU29g/actuele-beschikbaarheid-parkeergarages/)
[The dataset to all your questions](https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstleyVEVO)

**Comment by jonahgoldwastaken** [comment]
Thanks voor de dataset! Ga alleen een andere weg inslaan waardoor ik dit niet meer echt zou kunnen gebruiken.
