### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Vincentvanleeuwen** [theonejonahgold/functional-programming#3]
# Readme & Wiki
## Tops

- Great structure of your readme!
- The structure of your wiki is the same, fantastic!
- You described all the data from the datasets you've found very well.
- A real strong debriefing! Not too long, and to the point.
- You've got a nice modular project already, all the principles of functional programming are applied, and you're even using typescript!

### General
- [x] If I were you, I'd change the language from the readme to Dutch, because you are referring to a Dutch wiki.
- [x]  I'd put your code editor files in your .gitignore as well (.nova & .vscode).
- [x]  You've forgotten to add a repo description! (Don't worry, I forgot it too)

### Data
- [x]  It's best if you'd also write down what is done with invalid or empty values within each data set.

### Wiki
- [x] It might be nice to add the functional patterns you've described in your readme to the table of contents.
- [x]  It might be interesting for the reader to know if you've found invalid values and how you've dealt with these.
- [x]  In "RDW Data verwerken" & "Oefenen met survey data" you've placed pictures that are barely readable, maybe try cutting these up into multiple pictures?
- [x]  On the page "Week 2" it says: "Proces logboek week 1"

### Code
- [x]  It would be nice to see a couple comments to better understand your code!

## Grading
- Application of subject matter
I can only give a **5-6** since we all haven't touched d3.js yet.
- Understanding
I get the feeling you understand everything you're using. When I ask you for instance about the pipe() function you're using in your code you can give me a great explanation on what it is and how it works. **9-10**
- Quality
You've put a lot of effort in your wiki and your code. The only thing about your code is that it's missing comments, other than that you're doing everything quite perfectly. **7-8**
- Process
You've shown your process on the RDW Data. What I'm missing is a couple code examples. Maybe you could show a code example you tried to apply to your code but didn't work, and then show the solution you've found to fix this problem. **3-4**

**Comment by jonahgoldwastaken** [comment]
# Fixes deviating from the fixes provided by the feedback

- I won't translate the README. The distinction between the wiki and the README is that the wiki is for the teachers and the README is for outside world. If anything I'd translate the wiki to English, but I won't do that as it is too much work to put myself through with the time I have.
- Removed vscode folder, but kept the nova folder as that is my code editor of choice. Other people using Nova will have the same settings applied, which creates a consistent development environment for everyone developing on this repo.
- Fixed large image issue by adding a link to the image underneath it for easy zooming.
