### ISSUE TITLE
Feedback hoofdvraag

### ISSUE THREAD

**Issue by chelseadoeleman** [theonejonahgold/functional-programming#4]
Hi Jonah! 

Wow super interessante onderzoeksvraag ben benieuwd wat hier uit gaat komen! 😊 Je deelvragen zeggen goed wat je wil onderzoeken, alleen door de formulering van je hoofdvraag lijkt het net alsof je het met nog iets wil vergelijken klopt dat?

**Comment by jonahgoldwastaken** [comment]
Hi Chelsea! Dankjewel! Waaraan merk je dit? Dat is namelijk niet de bedoeling 😅

**Comment by chelseadoeleman** [comment]
Haha dat dacht ik al, anders wilde ik zeggen dat het misschien wel te groot wordt. Kan zijn dat ik de vraag niet goed heb begrepen😉, maar je hebt het over hoe parkeergarages zich verhouden (of ondersteunen) tot de 24-uurs economie. Hierdoor klonk het alsof je het tegen een andere dataset aan wilde houden met andere faciliteiten die 24 uur open zijn. 

Als ik dit verkeerd heb begrepen dan kun je dit gewoon negeren en anders misschien de hoofdvraag herformuleren, want je deelvragen waren top! 😊

**Comment by jonahgoldwastaken** [comment]
Ah zo! Het leuke is dat dat inderdaad ook de intentie was, totdat ik erachter kwam dat het samenvoegen van dat soort data **heel veel** tijd in beslag zal nemen. Ik zal kijken hoe ik de hoofdvraag kan herformuleren. Heb je daar misschien tips voor?

**Comment by chelseadoeleman** [comment]
Gelukkig! Als je tijd over hebt en het leuk vindt go for it, maar anders zou ik het voor nu laten haha. 
Oeh goeie, uhm belangrijk is dat de vraag zo open mogelijk is wat je al heel goed had gedaan. Misschien bijvoorbeeld: 

**Hoe toegankelijk(bereikbaar) zijn parkeergarages door de dag heen?**
*Ik zou dit zeker nog herformuleren :)*

Dit is het eerste wat bij mij naar boven komt bij het lezen van je deelvragen. Je zou als visualisatie dan ook evt kunnen denken aan een interactieve tijdlijn, wanneer je bij bepaalde parkeergarages terecht kan en welke het voordeligst zijn.

**Comment by jonahgoldwastaken** [comment]
Dit vind ik een hele goeie! Ga ik zeker meenemen in mijn brainstorm. Thanks! 😊
